# Самые необходимые типы данных

[К оглавлению](00_contents.ipynb)

**Тип данных** позволяет указать компьютеру, какие действия можно выполнять с этими данными и как это делать.

Наиболее часто использьуемые типы данных приведены в таблице

Тип данных | Применение
:----------|:-----------------------------------------
int        | Целые числа
float      | Действительные числа
bool       | Логические значения
str        | Строки
list       | Списки - упорядоченные последовательности значений (изменяемые)
tuple      | Кортежи - упорядоченные последовательности значений (неизменяемые)
dict       | Словари - коллекции объектов с доступом по ключу
ndarray    | Массивы numpy
None       | Пустое значение

Тип объекта можно узнать с помощью функции `type()`

In [1]:
type(3)

int

In [2]:
type(3.)

float

In [3]:
type('ноль')

str

In [4]:
type(False)

bool

## Простые типы данных

### Числовые типы данных

Два наиболее часто используемых числовых типа данных - целые (`int`) и действительные (`float`) числа.

При необходимости, *преобразование типов* происходит автоматически. Если в выражении содержится хотя бы одно действительное число, то результат будет действительным числом.

In [5]:
2 * 2

4

In [6]:
2 * 2.

4.0

In [7]:
5 / 2 # 2.5 в Python 3, но 2 в Python 2 

2.5

### Логический тип данных

Логический тип данных представлен двумя константами - `True` и `False`

Результат логического типа часто появляется в операциях сравнения:

In [8]:
5 > 2

True

In [9]:
2 * 2 == 5

False

In [10]:
2 * 2 != 5

True

In [11]:
'Колбаса' > 'Бутерброд'

True

In [12]:
print(ord('К'), ord('Б')) #Коды символов К и Б

1050 1041


Можно комбинировать несколько логических выражений с помощью логических операторов: `and`, `or`, `not`

In [13]:
5 > 2 and 'a' < 'b'

True

In [14]:
not 5 > 2

False

In [15]:
not 5 > 2 or 2 * 2 == 4

True

### Строки

In [16]:
s = 'Сочи '

In [17]:
s2 = 'Море'
s + s2

'Сочи Море'

In [18]:
y = 2014
s + y #ошибка!

TypeError: Can't convert 'int' object to str implicitly

In [19]:
s + str(y) #правильно: приведение типа к строковому типу

'Сочи 2014'

Сложные строки при выводе результатов расчета удобно получать с помощью оператора форматированного вывода %

In [20]:
r = 10
from math import pi
print('Площадь круга радиусом %s равна %s' % (r, pi * r**2)) #формат по умолчанию

Площадь круга радиусом 10 равна 314.1592653589793


In [21]:
print('Площадь круга радиусом %.1f равна %.2f' % (r, pi * r**2)) #заданный формат

Площадь круга радиусом 10.0 равна 314.16


[Справочник по форматам](https://docs.python.org/2/library/string.html#formatspec)

Количество цифр после запятой можно также задавать с помощью волшебной команды `%precision`, но это будет работать не везде.

### Пустое значение

Чтобы показать, что имя переменной не связано ни с каким объектом, в Python используется специальное значение: `None`

In [22]:
x = None
print(x)
type(x)

None


NoneType

In [23]:
x is None #проверка на пустое значение

True

## Коллекции

Типы-коллекции содержат большое количество элементов. В Python множество инструментов для удобной обработки коллекций.

### Списки
_Список_ (_list_) позволяет создать коллекцию объектов любого типа.

In [24]:
l = [1, 2., 'три', False]

Нумерация элементов в Python начинается от нуля.

![Индексирование элементов списка](pics/list_indexing.svg 'Индексирование элементов списка')


Диапазон значений можно указать с помощью двоеточия: `[a:b]`

Обратите внимание, что правая граница (`b`) не включается в диапазон!


Извлечение элементов:

In [25]:
print(l)
l[0] #нумерация элементов начинается с нуля

[1, 2.0, 'три', False]


1

In [26]:
print(l)
l[-1] #последний элемент

[1, 2.0, 'три', False]


False

In [27]:
print(l)
l[1:3] #элементы с индексами 1 и 2. NB: Элемент 3 не включается!

[1, 2.0, 'три', False]


[2.0, 'три']

In [28]:
print(l)
l[2:] #все элементы, начиная с индекса 2 и до конца списка

[1, 2.0, 'три', False]


['три', False]

In [29]:
print(l)
l + l #слияние списков

[1, 2.0, 'три', False]


[1, 2.0, 'три', False, 1, 2.0, 'три', False]

In [30]:
print(s)
l2 = list(s) #список из строки
print(l2)

Сочи 
['С', 'о', 'ч', 'и', ' ']


Список - _изменяемый_ тип данных (_mutable_)

In [31]:
print(l)
l[2] = 3
l

[1, 2.0, 'три', False]


[1, 2.0, 3, False]

### Кортежи

_Кортеж_ (_tuple_) позволяет создать коллекцию объектов любого вида, однако, в отличие от списка, элементы этой коллекции нельзя менять после создания. Кортеж - _неизменяемый_ тип (_immutable_)

In [32]:
t = (1, 2., 'три', False)

In [33]:
t[1:2]

(2.0,)

In [34]:
t[2] = 3 #ошибка!

TypeError: 'tuple' object does not support item assignment

In [35]:
t + t #новый кортеж, составленный из двух копий t

(1, 2.0, 'три', False, 1, 2.0, 'три', False)

### Словари

_Словарь_ (_dict_) позволяет создавать коллекцию объектов любого вида. Однако для выбора _значений_ (_values_) из коллекции используются не индексы, а _ключи_ (_keys_)

![Словарь](pics/dic_indexing.svg 'Ключи и значения в словаре')

Ключом может быть любой неизменяемый объект. Значение может быть любым объектом.

In [36]:
mydict = {'звери': ['собака', 'крот', 'утконос'],
         'птицы': ['дятел', 'дрофа']}

In [37]:
mydict['птицы'] #извлечение значения по ключу

['дятел', 'дрофа']

In [38]:
mydict['деревья'] = ['дуб', 'баобаб']
mydict

{'деревья': ['дуб', 'баобаб'],
 'звери': ['собака', 'крот', 'утконос'],
 'птицы': ['дятел', 'дрофа']}

In [39]:
mydict[0] #ошибка - элементы словаря не упорядочены, поэтому нельзя использовать числовые индексы

KeyError: 0

In [40]:
mydict['грибы'] #ошибка - такого ключа нет

KeyError: 'грибы'

## Объекты

Все типы данных в Python являются _объектными_. Объекты, помимо самих данных, содержат также и _методы_, позволяющие эти данные обрабатывать.

In [41]:
x = 5.0
print(x)
type(x)

5.0


float

In [42]:
print(dir(x))

['__abs__', '__add__', '__bool__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getformat__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__int__', '__le__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__pos__', '__pow__', '__radd__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmod__', '__rmul__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__setattr__', '__setformat__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', 'as_integer_ratio', 'conjugate', 'fromhex', 'hex', 'imag', 'is_integer', 'real']


Для доступа к членам класса - вызова методов, или просмотра/изменения атрибутов используется "запись с точкой":   
- `объектная_переменная.метод()` 
- `объектная_переменная.имя_атрибута`

In [43]:
x.imag # Мнимая часть числа

0.0

In [44]:
print(s)
type(s)

Сочи 


str

In [45]:
print(dir(s))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


Если в блокноте сразу после ввода точки нажать клавишу `Tab`, то выводится подсказка по методам и атрибутам объекта, на который ссылается переменная

In [46]:
# Попробуйте здесь получить подсказку по методам объекта-строки (переменная s)



In [47]:
s.upper()

'СОЧИ '

In [48]:
s.upper().strip()

'СОЧИ'

In [49]:
print(l)
type(l)

[1, 2.0, 3, False]


list

In [50]:
print(dir(l))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [51]:
l.reverse() #список изменяется "на месте"
print(l)

[False, 3, 2.0, 1]


Чтобы задать, какие атрибуты (данные) и методы (операции) будут у объекта, разработчики создают _классы_.  Объектно-ориентированный подход упрощает разработку программ, потому что классы скрывают детали реализации от пользователя. Чтобы воспользоваться объектом, достаточно знать, какие методы он поддерживает и правила использования этих методов. Во многих случаях (например, при сравнениях, выполнении арифметических операций, при печати) нужные методы вызываются автоматически.

In [52]:
list?

В определение класса может быть включен специальный метод - `__init__()` (_конструктор_). Конструктор автоматически выполняется при создании нового объекта на основе данного класса. Это позволяет сразу при создании получить объект с нужными свойствами. Данные для этого передаются через аргументы конструктора. При использовании инициализации объекта в программе, необходимо указывать эти аргументы в скобках после имени класса.

## Массивы numpy

_Массив_ (_array_) - тип данных, предназначенный для обработки табличных данных. Определение этого типа данных и функции для работы с массивами содержатся в пакете `numpy`.

In [53]:
import numpy as np

#### Создание массивов

In [54]:
arr1 = np.array([10, 20, 25, 32]) #массив из списка
print(arr1)
type(arr1)

[10 20 25 32]


numpy.ndarray

In [55]:
arr1.shape #форма массива

(4,)

In [56]:
arr1.ndim #число измерений

1

In [57]:
#двухмерный массив из списка:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
arr2.shape

(3, 3)

In [59]:
arr2.ndim

2

In [60]:
I = np.identity(5) #единичная матрица
print(I)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [61]:
I.shape

(5, 5)

In [62]:
I.ndim

2

In [63]:
A = np.zeros((3, 4))
print(A)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [64]:
x = np.arange(-10, 11, 2)
x

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [65]:
y = np.linspace(-10, 10, 11)
y

array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.,  10.])

In [66]:
print(x.dtype, y.dtype)

int32 float64


In [67]:
print(x.nbytes, y.nbytes)

44 88


#### Операции с массивами

In [68]:
A[1, 1] = 5 #изменение элемента
print(A)

[[ 0.  0.  0.  0.]
 [ 0.  5.  0.  0.]
 [ 0.  0.  0.  0.]]


In [69]:
A[1:, 2:] = 10
print(A)

[[  0.   0.   0.   0.]
 [  0.   5.  10.  10.]
 [  0.   0.  10.  10.]]


In [70]:
print(A[1]) #извлечение строки

[  0.   5.  10.  10.]


In [71]:
print(A[:, 1]) #извлечение столбца

[ 0.  5.  0.]


In [72]:
print(A * 2) #полэлементное умножение

[[  0.   0.   0.   0.]
 [  0.  10.  20.  20.]
 [  0.   0.  20.  20.]]


In [73]:
print(A * A)

[[   0.    0.    0.    0.]
 [   0.   25.  100.  100.]
 [   0.    0.  100.  100.]]


In [74]:
print(np.sqrt(A * A)) #применение функции к каждому элементу массива

[[  0.   0.   0.   0.]
 [  0.   5.  10.  10.]
 [  0.   0.  10.  10.]]


In [75]:
print(A.T) #транспонирование

[[  0.   0.   0.]
 [  0.   5.   0.]
 [  0.  10.  10.]
 [  0.  10.  10.]]


In [76]:
B = A #переменная B ссылается на тот же массив, что и переменная A
B[0, 0] = 33
print(B)

[[ 33.   0.   0.   0.]
 [  0.   5.  10.  10.]
 [  0.   0.  10.  10.]]


In [77]:
print(A) #массив изменился, поэтому ссылка A также показывает измененный вариант

[[ 33.   0.   0.   0.]
 [  0.   5.  10.  10.]
 [  0.   0.  10.  10.]]


In [78]:
C = A.copy() #создается копия массива
C[0, 0] = 55
print(C) 

[[ 55.   0.   0.   0.]
 [  0.   5.  10.  10.]
 [  0.   0.  10.  10.]]


In [79]:
print(A) #оригинал не изменился

[[ 33.   0.   0.   0.]
 [  0.   5.  10.  10.]
 [  0.   0.  10.  10.]]
